vim.g.mapleader = " "
vim.g.maplocalleader = " "

local map = vim.keymap.set

map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
map({ "n", "x" }, "<Down>", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
map({ "n", "x" }, "<Up>", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
map("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window", remap = true })
map("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window", remap = true })
map("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window", remap = true })
map("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window", remap = true })
map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase Window Height" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease Window Height" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease Window Width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase Window Width" })
map("n", "<A-j>", "<cmd>execute 'move .+' . v:count1<cr>==", { desc = "Move Down" })
map("n", "<A-k>", "<cmd>execute 'move .-' . (v:count1 + 1)<cr>==", { desc = "Move Up" })
map("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
map("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
map("v", "<A-j>", ":<C-u>execute \"'<,'>move '>+\" . v:count1<cr>gv=gv", { desc = "Move Down" })
map("v", "<A-k>", ":<C-u>execute \"'<,'>move '<-\" . (v:count1 + 1)<cr>gv=gv", { desc = "Move Up" })
map("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next Buffer" })
map("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Previous Buffer" })
map("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
map("n", "<leader>bd", "<cmd>confirm bdelete<cr>", { desc = "Delete Buffer" })
map("n", "<leader>bo", "<cmd>%bdelete|edit #<cr>", { desc = "Delete Other Buffers" })
map("n", ";", ":", { desc = "Command mode" })
map("n", "<leader>w", "<Cmd>write<CR>", { silent = true, desc = "Save file" })
map("n", "<leader>q", "<Cmd>confirm bdelete<CR>", { silent = true, desc = "Delete buffer" })
map("n", "<C-q>", "<Cmd>confirm quit<CR>", { silent = true, desc = "Quit" })
map("n", "<Tab>", "<Cmd>bnext<CR>", { silent = true, desc = "Next buffer" })
map("n", "<S-Tab>", "<Cmd>bprevious<CR>", { silent = true, desc = "Previous buffer" })
map("n", "<leader>sv", "<Cmd>vsplit<CR>", { silent = true, desc = "Split vertically" })
map("n", "<leader>sh", "<Cmd>split<CR>", { silent = true, desc = "Split horizontally" })
map("n", "<leader>se", "<C-w>=", { silent = true, desc = "Equalize windows" })
map("n", "<leader>sx", "<Cmd>close<CR>", { silent = true, desc = "Close window" })
map("n", "<leader>to", "<Cmd>tabnew<CR>", { silent = true, desc = "Open tab" })
map("n", "<leader>tn", "<Cmd>tabnext<CR>", { silent = true, desc = "Next tab" })
map("n", "<leader>tp", "<Cmd>tabprevious<CR>", { silent = true, desc = "Previous tab" })
map("n", "<leader>tx", "<Cmd>tabclose<CR>", { silent = true, desc = "Close tab" })
map("n", "<leader>tf", "<Cmd>tabfirst<CR>", { silent = true, desc = "First tab" })
map("n", "<leader>tl", "<Cmd>tablast<CR>", { silent = true, desc = "Last tab" })
map("n", "<Esc>", "<Esc><Cmd>noh<CR><Esc>", { silent = true })
map("n", "<CR>", "o<Esc>", { silent = true })
map("n", "<S-CR>", "O<Esc>", { silent = true })
map({ "i", "n", "s" }, "<esc>", function()
	vim.cmd("noh")
	return "<esc>"
end, { expr = true, desc = "Escape and Clear hlsearch" })
map("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, desc = "Next Search Result" })
map("x", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
map("o", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
map("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, desc = "Prev Search Result" })
map("x", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
map("o", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
map("i", ",", ",<c-g>u")
map("i", ".", ".<c-g>u")
map("i", ";", ";<c-g>u")
map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save File" })
map("x", "<", "<gv")
map("x", ">", ">gv")
map({ "n", "x" }, "<leader>cf", "<cmd>Format<cr>", { desc = "Format" })

local diagnostic_goto = function(next, severity)
	return function()
		vim.diagnostic.jump({
			count = (next and 1 or -1) * vim.v.count1,
			severity = severity and vim.diagnostic.severity[severity] or nil,
			float = true,
		})
	end
end

map("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line Diagnostics" })
map("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
map("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
map("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Error" })
map("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Error" })
map("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Warning" })
map("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })

vim.keymap.set("n", "<leader>ss", "<cmd>SessionManager load_session<CR>")
vim.keymap.set("n", "<leader>sn", "<cmd>SessionManager save_current_session<CR>")
vim.keymap.set("n", "<leader>sd", "<cmd>SessionManager delete_session<CR>")
