require("plugins.packages")

require("plugins.treesitter")
require("plugins.ui")
require("plugins.bufferline")
require("plugins.oil")
require("plugins.telescope")
require("plugins.workflow")
require("plugins.indent")
require("plugins.editor")
require("plugins.which-key")
require("plugins.lsp")
