require("plugins.packages")

require("plugins.treesitter")
require("plugins.obsidian")
require("plugins.ui")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.editor")
require("plugins.which-key")
require("plugins.lsp")
