local harpoon = require("harpoon")
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

harpoon.setup()

local map = vim.keymap.set
map("n", "<leader>ha", function()
	mark.add_file()
end, { silent = true, desc = "Harpoon add file" })
map("n", "<leader>hm", function()
	ui.toggle_quick_menu()
end, { silent = true, desc = "Harpoon menu" })
map("n", "<leader>h1", function()
	ui.nav_file(1)
end, { silent = true, desc = "Harpoon file 1" })
map("n", "<leader>h2", function()
	ui.nav_file(2)
end, { silent = true, desc = "Harpoon file 2" })
map("n", "<leader>h3", function()
	ui.nav_file(3)
end, { silent = true, desc = "Harpoon file 3" })
map("n", "<leader>h4", function()
	ui.nav_file(4)
end, { silent = true, desc = "Harpoon file 4" })
